### ISSUE TITLE
.

### ISSUE THREAD

**Issue by hcxgs** [lenethx/amogus.ar#1]
hace que se vea la casa de la persona, no solo la ciudad

**Comment by lenethx** [comment]
I’d just like to interject for a moment. What you’re refering to as organs, is in fact, persona/organs, or as I’ve recently taken to calling it, persona plus organs. organs is not a living being system unto itself, but rather another free component of a fully functioning persona system made useful by the persona corelibs, shell utilities and vital system components comprising a full living being as defined by POSIX.

Many computer users run a modified version of the persona system every day, without realizing it. Through a peculiar turn of events, the version of persona which is widely used today is often called “organs”, and many of its users are not aware that it is basically the persona system, developed by the persona Project.

There really is a organs, and these people are using it, but it is just a part of the system they use. organs is the kernel: the program in the system that allocates the machine’s resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. organs is normally used in combination with the persona operating system: the whole system is basically persona with organs added, or persona/organs. All the so-called “organs” distributions are really distributions of persona/organs.
